### ISSUE TITLE
Updating to “zotero-citations@0.15.0” failed

### ISSUE THREAD

**Issue by oztalha** [retorquere/zotero-citations#23]
1. Just click update from 0.14.0

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.235.1

### Stack Trace

Uncaught TypeError: Cannot read property 'substr' of null

```
At C:\Users\Talha\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-card.js:709

TypeError: Cannot read property 'substr' of null
    at C:\Users\Talha\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-card.js:709:80
    at C:\Users\Talha\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:376:51
    at C:\Users\Talha\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:403:20
    at exit (C:\Users\Talha\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\Talha\AppData\Local\atom\app-1.8.0\resources\app.asar\src\buffered-process.js:215:47)
    at C:\Users\Talha\AppData\Local\atom\app-1.8.0\resources\app.asar\src\buffered-process.js:222:18
    at Socket.<anonymous> (C:\Users\Talha\AppData\Local\atom\app-1.8.0\resources\app.asar\src\buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -1:56.1.0 pane:reopen-closed-item (ul.list-inline.tab-bar.inset-panel)
     -1:50.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "markdown-format",
      "markdown-mindmap",
      "markdown-themeable-pdf",
      "markdown-toc",
      "atom-markdown-katex",
      "language-gfm",
      "gfm-pdf"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
language-markdown, v0.14.0
language-pfm, v0.82.0
markdown-preview-plus, v2.4.0
minimap, v4.24.3
pandoc-convert, v1.0.4
pdf-view, v0.50.0
text-manipulation, v0.6.0

# Dev
No dev packages
```

**Comment by retorquere** [comment]
I have my defense tomorrow; I'm going to look at this in the weekend.

**Comment by retorquere** [comment]
I don't have access to Windows 10, but when I install Atom 1.8.0 and ZC 0.15, I get no errors in the settings view. I've looked through the source of settings-view, and the only place I can see that `substr` is being called is on the package SHA, and I think Atom is supposed to generate those by itself. Perhaps the settings-view author can shed more light on this.

**Comment by oztalha** [comment]
Oh, sorry for taking your time. The issue was fixed after a restart of the PC.
