### ISSUE TITLE
Problem with deasync binding file

### ISSUE THREAD

**Issue by Foucl** [retorquere/zotero-citations#34]
[Enter steps to reproduce below:]
1. Install zotero-citations
2. try to run Pick or Scan command

**Atom Version**: 1.9.0-beta0
**System**: KPP-5012-PC-1
**Thrown From**: [zotero-citations](https://github.com/ZotPlus/zotero-citations) package, v0.19.0
### Stack Trace

Failed to activate the zotero-citations package

```
At Could not locate the bindings file. Tried:
 → C:\Users\DDmitarbeiter\.atom\packages\zotero-citations\node_modules\deasync\build\deasync.node
 → C:\Users\DDmitarbeiter\.atom\packages\zotero-citations\node_modules\deasync\build\Debug\deasync.node
 → C:\Users\DDmitarbeiter\.atom\packages\zotero-citations\node_modules\deasync\build\Release\deasync.node
 → C:\Users\DDmitarbeiter\.atom\packages\zotero-citations\node_modules\deasync\out\Debug\deasync.node
 → C:\Users\DDmitarbeiter\.atom\packages\zotero-citations\node_modules\deasync\Debug\deasync.node
 → C:\Users\DDmitarbeiter\.atom\packages\zotero-citations\node_modules\deasync\out\Release\deasync.node
 → C:\Users\DDmitarbeiter\.atom\packages\zotero-citations\node_modules\deasync\Release\deasync.node
 → C:\Users\DDmitarbeiter\.atom\packages\zotero-citations\node_modules\deasync\build\default\deasync.node
 → C:\Users\DDmitarbeiter\.atom\packages\zotero-citations\node_modules\deasync\compiled\5.10.0\win32\ia32\deasync.node

Error: Could not locate the bindings file. Tried:
 → C:\Users\DDmitarbeiter\.atom\packages\zotero-citations\node_modules\deasync\build\deasync.node
 → C:\Users\DDmitarbeiter\.atom\packages\zotero-citations\node_modules\deasync\build\Debug\deasync.node
 → C:\Users\DDmitarbeiter\.atom\packages\zotero-citations\node_modules\deasync\build\Release\deasync.node
 → C:\Users\DDmitarbeiter\.atom\packages\zotero-citations\node_modules\deasync\out\Debug\deasync.node
 → C:\Users\DDmitarbeiter\.atom\packages\zotero-citations\node_modules\deasync\Debug\deasync.node
 → C:\Users\DDmitarbeiter\.atom\packages\zotero-citations\node_modules\deasync\out\Release\deasync.node
 → C:\Users\DDmitarbeiter\.atom\packages\zotero-citations\node_modules\deasync\Release\deasync.node
 → C:\Users\DDmitarbeiter\.atom\packages\zotero-citations\node_modules\deasync\build\default\deasync.node
 → C:\Users\DDmitarbeiter\.atom\packages\zotero-citations\node_modules\deasync\compiled\5.10.0\win32\ia32\deasync.node
    at bindings (C:\Users\DDmitarbeiter\.atom\packages\zotero-citations\node_modules\deasync\node_modules\bindings\bindings.js:88:9)
    at C:\Users\DDmitarbeiter\.atom\packages\zotero-citations\node_modules\deasync\index.js:34:32
    at Object.<anonymous> (C:\Users\DDmitarbeiter\.atom\packages\zotero-citations\node_modules\deasync\index.js:76:2)
    at Module._compile (C:\Users\DDmitarbeiter\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\DDmitarbeiter\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\DDmitarbeiter\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/DDmitarbeiter/.atom/packages/zotero-citations/lib/schomd.coffee:2:11)
    at Object.<anonymous> (file:///C:/Users/DDmitarbeiter/.atom/packages/zotero-citations/lib/schomd.coffee:1:1)
    at Module._compile (C:\Users\DDmitarbeiter\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\DDmitarbeiter\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\DDmitarbeiter\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/DDmitarbeiter/.atom/packages/zotero-citations/lib/zotero-citations.coffee:3:10)
    at Object.<anonymous> (file:///C:/Users/DDmitarbeiter/.atom/packages/zotero-citations/lib/zotero-citations.coffee:1:1)
    at Module._compile (C:\Users\DDmitarbeiter\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\DDmitarbeiter\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\DDmitarbeiter\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\DDmitarbeiter\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\package.js:715:27)
    at Package.module.exports.Package.activateNow (C:\Users\DDmitarbeiter\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\package.js:173:16)
    at C:\Users\DDmitarbeiter\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\package.js:795:25
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\DDmitarbeiter\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\DDmitarbeiter\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
```
### Commands

```
     -0:12.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:12.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:10.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:10.8.0 zotero-citations:pick (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "markdown-preview"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
gfm-pdf, v0.3.4 (inactive)
keyboard-localization, v1.4.18 (active)
language-pfm, v0.82.0 (active)
markdown-pdf, v1.5.0 (inactive)
markdown-preview-plus, v2.4.0 (active)
zotero-citations, v0.19.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.2.0 (active)
git-diff, v1.0.1 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.3.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

I also tried to manually create a build folder in C:\Users\DDmitarbeiter.atom\packages\zotero-citations\node_modules\deasync\ and copy the correct deasync.node (win32-x64-node-4 as node -v yields 'v4.4.7')  file from \bin in there. Then the error is as follows: 

```
error: 193\\?\C:\Users\DDmitarbeiter\.atom\packages\zotero-citations\node_modules\deasync\build\deasync.node
Hide Stack Trace
Error: error: 193\\?\C:\Users\DDmitarbeiter\.atom\packages\zotero-citations\node_modules\deasync\build\deasync.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:440:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\DDmitarbeiter\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\native-compile-cache.js:50:27)
    at bindings (C:\Users\DDmitarbeiter\.atom\packages\zotero-citations\node_modules\deasync\node_modules\bindings\bindings.js:76:44)
    at C:\Users\DDmitarbeiter\.atom\packages\zotero-citations\node_modules\deasync\index.js:34:32
    at Object.<anonymous> (C:\Users\DDmitarbeiter\.atom\packages\zotero-citations\node_modules\deasync\index.js:76:2)
    at Module._compile (C:\Users\DDmitarbeiter\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\DDmitarbeiter\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\DDmitarbeiter\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/DDmitarbeiter/.atom/packages/zotero-citations/lib/schomd.coffee:2:11)
    at Object.<anonymous> (file:///C:/Users/DDmitarbeiter/.atom/packages/zotero-citations/lib/schomd.coffee:1:1)
    at Module._compile (C:\Users\DDmitarbeiter\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\DDmitarbeiter\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\DDmitarbeiter\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/DDmitarbeiter/.atom/packages/zotero-citations/lib/zotero-citations.coffee:3:10)
    at Object.<anonymous> (file:///C:/Users/DDmitarbeiter/.atom/packages/zotero-citations/lib/zotero-citations.coffee:1:1)
    at Module._compile (C:\Users\DDmitarbeiter\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\DDmitarbeiter\AppData\Local\atom\app-1.9.0-beta0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
```

**Comment by retorquere** [comment]
I'm trying to find a way to do without deasync, but atom currently doesn't have a way to "lock" the editor while I am processing the markdown.

**Comment by retorquere** [comment]
deasync has been removed.
