### ISSUE TITLE
zotero-citations disabled by Atom

### ISSUE THREAD

**Issue by rmzelle** [retorquere/zotero-citations#35]
Atom 1.8.0 disabled my copy of zotero-citations 0.19.0 with the error messages:

> Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.

along with a bunch of "deasync@0.1.7 – Could not locate the bindings file. Tried: → [paths]" error messages. Haven't tried the "Rebuild Packages" button yet that pops up.

**Comment by rmzelle** [comment]
I tried rebuilding it, which worked, but the "Scan" command still triggers the same errors:

```
Error: Could not locate the bindings file. Tried:
 → C:\Users\<user>\.atom\packages\zotero-citations\node_modules\deasync\build\deasync.node
 → C:\Users\<user>\.atom\packages\zotero-citations\node_modules\deasync\build\Debug\deasync.node
 → C:\Users\<user>\.atom\packages\zotero-citations\node_modules\deasync\build\Release\deasync.node
 → C:\Users\<user>\.atom\packages\zotero-citations\node_modules\deasync\out\Debug\deasync.node
 → C:\Users\<user>\.atom\packages\zotero-citations\node_modules\deasync\Debug\deasync.node
 → C:\Users\<user>\.atom\packages\zotero-citations\node_modules\deasync\out\Release\deasync.node
 → C:\Users\<user>\.atom\packages\zotero-citations\node_modules\deasync\Release\deasync.node
 → C:\Users\<user>\.atom\packages\zotero-citations\node_modules\deasync\build\default\deasync.node
 → C:\Users\<user>\.atom\packages\zotero-citations\node_modules\deasync\compiled\5.1.1\win32\ia32\deasync.node
    at bindings (C:\Users\<user>\.atom\packages\zotero-citations\node_modules\deasync\node_modules\bindings\bindings.js:88:9)
    at C:\Users\<user>\.atom\packages\zotero-citations\node_modules\deasync\index.js:34:32
    at Object.<anonymous> (C:\Users\<user>\.atom\packages\zotero-citations\node_modules\deasync\index.js:76:2)
    at Module._compile (C:\Users\<user>\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\<user>\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\<user>\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/<user>/.atom/packages/zotero-citations/lib/schomd.coffee:2:11)
    at Object.<anonymous> (file:///C:/Users/<user>/.atom/packages/zotero-citations/lib/schomd.coffee:1:1)
    at Module._compile (C:\Users\<user>\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\<user>\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\<user>\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/<user>/.atom/packages/zotero-citations/lib/zotero-citations.coffee:3:10)
    at Object.<anonymous> (file:///C:/Users/<user>/.atom/packages/zotero-citations/lib/zotero-citations.coffee:1:1)
    at Module._compile (C:\Users\<user>\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\<user>\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\<user>\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\<user>\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:715:27)
    at Package.module.exports.Package.activateNow (C:\Users\<user>\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:173:16)
    at C:\Users\<user>\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:795:25
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\<user>\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\<user>\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
```

**Comment by retorquere** [comment]
I'm looking to do away with the async stuff altogether, but I haven't found a way yet to safely "lock" the editor while the scanner runs.

**Comment by amirzolal** [comment]
Same issue as with the deasync bug report - after rebuilding the package it throws these errors. I thought I had a problem with my installation before noticing these bug reports. 
I hope you can fix it, zotero-citations in combination with atom is the best thing that happenned to me since a long time.

A

**Comment by retorquere** [comment]
It's fixable, but it requires a mess of asynchronous callbacks. I'm working my way through them.

**Comment by retorquere** [comment]
It should now update.
