### ISSUE TITLE
cannot install zotero-citations

### ISSUE THREAD

**Issue by tluge** [retorquere/zotero-citations#36]
[Enter steps to reproduce below:]

1. Open package manager
2. Install zotero-citations
Result: Atom throws errors and aborts installation.

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Microsoft Windows 10 Home Single Language
**Thrown From**: [zotero-citations](https://github.com/ZotPlus/zotero-citations) package, v0.19.0

### Stack Trace

Uncaught Error: Could not locate the bindings file. Tried:
 → C:\Users\User\.atom\packages\zotero-citations\node_modules\deasync\build\deasync.node
 → C:\Users\User\.atom\packages\zotero-citations\node_modules\deasync\build\Debug\deasync.node
 → C:\Users\User\.atom\packages\zotero-citations\node_modules\deasync\build\Release\deasync.node
 → C:\Users\User\.atom\packages\zotero-citations\node_modules\deasync\out\Debug\deasync.node
 → C:\Users\User\.atom\packages\zotero-citations\node_modules\deasync\Debug\deasync.node
 → C:\Users\User\.atom\packages\zotero-citations\node_modules\deasync\out\Release\deasync.node
 → C:\Users\User\.atom\packages\zotero-citations\node_modules\deasync\Release\deasync.node
 → C:\Users\User\.atom\packages\zotero-citations\node_modules\deasync\build\default\deasync.node
 → C:\Users\User\.atom\packages\zotero-citations\node_modules\deasync\compiled\5.10.0\win32\ia32\deasync.node

```
At C:\Users\User\.atom\packages\zotero-citations\node_modules\bindings\bindings.js:91

Error: Could not locate the bindings file. Tried:
 → C:\Users\User\.atom\packages\zotero-citations\node_modules\deasync\build\deasync.node
 → C:\Users\User\.atom\packages\zotero-citations\node_modules\deasync\build\Debug\deasync.node
 → C:\Users\User\.atom\packages\zotero-citations\node_modules\deasync\build\Release\deasync.node
 → C:\Users\User\.atom\packages\zotero-citations\node_modules\deasync\out\Debug\deasync.node
 → C:\Users\User\.atom\packages\zotero-citations\node_modules\deasync\Debug\deasync.node
 → C:\Users\User\.atom\packages\zotero-citations\node_modules\deasync\out\Release\deasync.node
 → C:\Users\User\.atom\packages\zotero-citations\node_modules\deasync\Release\deasync.node
 → C:\Users\User\.atom\packages\zotero-citations\node_modules\deasync\build\default\deasync.node
 → C:\Users\User\.atom\packages\zotero-citations\node_modules\deasync\compiled\5.10.0\win32\ia32\deasync.node
    at bindings (C:\Users\User\.atom\packages\zotero-citations\node_modules\bindings\bindings.js:88:9)
    at C:\Users\User\.atom\packages\zotero-citations\node_modules\deasync\index.js:34:32
    at Object.<anonymous> (C:\Users\User\.atom\packages\zotero-citations\node_modules\deasync\index.js:76:2)
    at Module._compile (C:\Users\User\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\User\AppData\Local\atom\app-1.10.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\User\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/User/.atom/packages/zotero-citations/lib/schomd.coffee:2:11)
    at Object.<anonymous> (file:///C:/Users/User/.atom/packages/zotero-citations/lib/schomd.coffee:1:1)
    at Module._compile (C:\Users\User\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\User\AppData\Local\atom\app-1.10.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\User\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/User/.atom/packages/zotero-citations/lib/zotero-citations.coffee:3:10)
    at Object.<anonymous> (file:///C:/Users/User/.atom/packages/zotero-citations/lib/zotero-citations.coffee:1:1)
    at Module._compile (C:\Users\User\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\User\AppData\Local\atom\app-1.10.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\User\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\User\AppData\Local\atom\app-1.10.2\resources\app.asar\src\package.js:718:27)
    at Package.module.exports.Package.activateConfig (C:\Users\User\AppData\Local\atom\app-1.10.2\resources\app.asar\src\package.js:225:12)
    at PackageManager.module.exports.PackageManager.packageHasSettings (C:\Users\User\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:55:14)
    at PackageCard.module.exports.PackageCard.hasSettings (C:\Users\User\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\settings-view\lib\package-card.js:699:34)
    at PackageCard.module.exports.PackageCard.updateSettingsState (C:\Users\User\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\settings-view\lib\package-card.js:397:16)
    at PackageCard.module.exports.PackageCard.updateInterfaceState (C:\Users\User\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\settings-view\lib\package-card.js:390:12)
    at C:\Users\User\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\settings-view\lib\package-card.js:643:24
    at C:\Users\User\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\settings-view\lib\package-card.js:712:20
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\User\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\User\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (C:\Users\User\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:680:27)
    at C:\Users\User\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:468:26
    at exit (C:\Users\User\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\User\AppData\Local\atom\app-1.10.2\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\User\AppData\Local\atom\app-1.10.2\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

### Commands

```
  3x -0:56.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:54.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "markdown-preview",
      "markdown-scroll-sync"
    ]
  }
}
```

### Installed Packages

```coffee
# User
git-plus, v5.17.1 (inactive)
markdown-folder, v0.5.0 (active)
markdown-preview-plus, v2.4.0 (active)
markdown-scroll-sync, v2.1.2 (inactive)
markdown-writer, v2.6.1 (active)
zotero-citations, v0.19.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by tluge** [comment]
Follow-up: this was on a Windows machine. The package did install, but not properly. The menu item under "Packages" was not created. But it was in fact installed, since it was listed in the "install" section of the Settings.

On Linux, no such problems. There the packages installs fine and runs (although I still have to figure out a strange issue).

**Comment by retorquere** [comment]
I need to figure out a way to get this package to work with asynchronous http requests. Electron/node really don't like my use of synchronous requests.

**Comment by tluge** [comment]
In that case it's the same issue as the previous bug report. I will close it.
