### ISSUE TITLE
Error When using Pick Citation Keybind on Ubuntu 20.04

### ISSUE THREAD

**Issue by ReedMerrill** [retorquere/zotero-citations#59]
[Enter steps to reproduce:]

1. On the first attempt to insert a citation using ctrl-alt-p an error message is generated, and no citation is inserted. 

Note that I have vim-mode-plus installed, but there is not a conflicting keybind with that package. The keybind doesn't work in insert mode or in normal mode.

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Ubuntu 20.04.2
**Thrown From**: [zotero-citations](ssh://git@github.com/retorquere/zotero-citations) package 5.4.2

### Stack Trace

Failed to activate the zotero-citations package

```
At ENOENT, node_modules/typescript/lib/lib.d.ts not found in /usr/share/atom/resources/app.asar

Error: ENOENT, node_modules/typescript/lib/lib.d.ts not found in /usr/share/atom/resources/app.asar
    at createError (electron/js2c/asar.js:111:17)
    at Object.fs.readFileSync (electron/js2c/asar.js:548:24)
    at TypeScriptSimple.createService (/app.asar/node_modules/typescript-simple/index.js:79:61)
    at TypeScriptSimple.compile (/app.asar/node_modules/typescript-simple/index.js:63:37)
    at Object.e.compile (/usr/share/atom/resources/app/static/<embedded>:11:582100)
    at Object.compile (/usr/share/atom/resources/app/static/<embedded>:11:577878)
    at compileFileAtPath (/usr/share/atom/resources/app/static/<embedded>:11:150953)
    at Object.value [as .ts] (/usr/share/atom/resources/app/static/<embedded>:11:153351)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:756277)
    at requireModule (/usr/share/atom/resources/app/static/<embedded>:14:1191586)
    at Package.requireMainModule (/usr/share/atom/resources/app/static/<embedded>:11:3400508)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:3388492)
    at /usr/share/atom/resources/app/static/<embedded>:14:1879
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1187631)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:351847)
    at KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:1226991)
    at KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1223125)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:286551)
```

### Commands

```
     -0:13.9.0 zotero-citations:pick (input.hidden-input)
```

### Non-Core Packages

```
contrast-syntax 0.8.1 
count-word 0.2.3 
pandoc-convert 1.1.1 
vim-mode-plus 1.36.4 
zotero-citations 5.4.2 
```

**Comment by KathyReid** [comment]
Following, I have exactly the same error. Can we revert to 5.5.0 as a workaround?

**Comment by retorquere** [comment]
I'm not sufficiently familiar with the atom ecosystem to know how to make a downgrade happen.

**Comment by retorquere** [comment]
I think I have removed 5.5.1

**Comment by KathyReid** [comment]
Ah, what's happening now that I'm back on `5.5.0` in Atom is that nothing happens when I choose "Zotero -> Pick" from the menu - there is also nothing shown in the developer console in Atom.

**Comment by retorquere** [comment]
I've just `apm link`ed the package and that works without an issue, but when I publish, I'm back to

```
Uncaught Exception:
Error: Cannot find module '/Users/emile/github/atom/src/main-process/start'
Require stack:
- /Applications/Atom.app/Contents/Resources/app.asar/src/main-process/main.js
- 
at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
at Function.o._resolveFilename (electron/js2c/browser_init.js:281:681)
at Module._load (internal/modules/cjs/loader.js:690:27)
at Function.Module._load (electron/js2c/asar.js:769:28)
at Module.require (internal/modules/cjs/loader.js:852:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/main-process/main.js:72:15)
at Module._compile (internal/modules/cjs/loader.js:967:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
at Module.load (internal/modules/cjs/loader.js:815:32)
```

I don't know what to do, and reporting the issue with Atom hasn't yet yielded any useful feedback. I don't know what to do here.

**Comment by retorquere** [comment]
The only thing I can think of right now is keep unpublishing packages until we hit one that works, but that's a bit ridiculous.

**Comment by retorquere** [comment]
Can someone help me to describe the problem better in https://github.com/atom/atom/issues/22432 ? I feel I'm not getting my point across, and I'm getting a bit fed up with doing battle with Atom to load the damn addon.

**Comment by KathyReid** [comment]
Quick note to say I'm at work at the moment, but will take a look tonight (in about 10 hours)

**Comment by retorquere** [comment]
It is acknowledged as a problem in atom. But I think I have a workaround for now.

**Comment by ReedMerrill** [comment]
Just updated to 5.7 and it now works!

**Comment by KathyReid** [comment]
Confirming `5.7.0` is working _perfectly_ under Ubuntu Linux 20.04 LTS. Thank you so much!
